In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([-0.2928568 , -0.47606429, -0.6754324 ,  0.94349833,  0.09946339,
        0.56425227,  2.13797739,  1.22955123,  0.53117948, -0.26730122])

In [8]:
B = np.random.randn(10)

In [9]:
b

NameError: name 'b' is not defined

In [10]:
B

array([ 0.70897512,  0.52564906,  0.33907761, -2.56122527,  0.27699561,
        0.25267362, -0.19637966,  1.18533681,  1.15491475,  0.5519327 ])

In [11]:
#Binary functions
np.add(A,B)

array([ 0.41611832,  0.04958477, -0.33635478, -1.61772695,  0.376459  ,
        0.81692589,  1.94159773,  2.41488803,  1.68609424,  0.28463147])

In [12]:
np.maximum(A,B)

array([ 0.70897512,  0.52564906,  0.33907761,  0.94349833,  0.27699561,
        0.56425227,  2.13797739,  1.22955123,  1.15491475,  0.5519327 ])