In [1]:
import numpy as np

In [2]:
from __future__ import division

In [3]:
5/2

2.5

In [11]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])

In [12]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr1 * arr1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [14]:
arr**3

NameError: name 'arr' is not defined

In [15]:
arr1**3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]])

In [16]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])